---
# defaults file for krb5_user

# Default domain admin password 
kerberos_user_password: pass
krb5_default_realm: DOMAIN.COM
krb5_domain_controller: dc01.domain.com
realm_domain: .DOMAIN.COM
kerberos_user: admin
ad_comoputer_ou: "CN=Computer,DC=domain,DC=com"
realm_domain_lc: domain.com
sssd_conf_path: /etc/sssd/sssd.conf
home_folder_auto_creation: true
use_fully_qualified_names: false

# The pam config to create home directories is really hit or miss for me
# I'm leaving it a separate varable for easy testing.
create_home_dirs: "{{ home_folder_auto_creation }}"

required_packages:
  - sssd-ad
  - sssd-tools
  - realmd
  - adcli
  - adsys