---
# defaults file for domain-join

required_packages:
  - sssd-ad
  - sssd-tools
  - realmd
  - adcli
  - adsys

# Default domain admin password. CHANGE THIS!!!
ad_admin_password: pass

domain_name: DOMAIN.COM
ad_admin_user: admin
ad_computer_ou: "CN=Computer,DC=domain,DC=com"
sssd_conf_path: /etc/sssd/sssd.conf
home_folder_auto_creation: true
use_fully_qualified_names: false

# The pam config to create home directories is really hit or miss for me
# I'm leaving it a separate varable for easy testing.
create_home_dirs: "{{ home_folder_auto_creation }}"