---

# Domain admin password 
kerberos_user_password: "{{ vault_domain_admin_pass }}"

domain_name: PLUMBUS.LAB
ad_admin_user: smiledt
ad_computer_ou: "OU=Linux Computers,OU=Plumbus Labs,DC=plumbus,DC=lab"
realm_domain_lc: plumbus.lab

home_dir_users:
  - smiledt